/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.model.Medico;
import br.senai.sp.jandira.model.OperacaoEnum;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282790
 */
public class MedicosDialog extends javax.swing.JDialog {

    private Medico medico;
    private OperacaoEnum operacao;

    //**Creates a New form MedicosDialog**
    public MedicosDialog(java.awt.Frame parent,
            boolean modal,
            OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        preencherTitulo();
    }

    public MedicosDialog(java.awt.Frame parent,
            boolean modal,
            OperacaoEnum operacao,
            Medico m) {
        super(parent, modal);
        initComponents();
        medico = m;
        this.operacao = operacao;
        preencherFormulario();
        preencherTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabeçalho = new javax.swing.JPanel();
        labelMedicoAdicionar = new javax.swing.JLabel();
        panelDetalhesMedico = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        textfieldCodigo = new javax.swing.JTextField();
        labelCrm = new javax.swing.JLabel();
        textFieldCrm = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        labelDataDeNascimento = new javax.swing.JLabel();
        formattedFieldDataDeNascimento = new javax.swing.JFormattedTextField();
        labelTabelaEspecialidades = new javax.swing.JLabel();
        labelEspecialidadesDoMedico = new javax.swing.JLabel();
        scrollTabelaEspecialidades = new javax.swing.JScrollPane();
        jListTabelaEspecialidades = new javax.swing.JList<>();
        buttonMoverEspecialidade1 = new javax.swing.JButton();
        buttonReturnEspecialidade = new javax.swing.JButton();
        scrollEspecialidadesdoMedico = new javax.swing.JScrollPane();
        jListEspecialidadesdoMedico = new javax.swing.JList<>();
        buttonCancelar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panelCabeçalho.setBackground(new java.awt.Color(204, 204, 204));
        panelCabeçalho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema de agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N
        panelCabeçalho.setLayout(null);

        labelMedicoAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelMedicoAdicionar.setForeground(new java.awt.Color(51, 0, 255));
        labelMedicoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/plus.png"))); // NOI18N
        labelMedicoAdicionar.setText("Médico - ADICIONAR");
        panelCabeçalho.add(labelMedicoAdicionar);
        labelMedicoAdicionar.setBounds(40, 30, 370, 40);

        getContentPane().add(panelCabeçalho);
        panelCabeçalho.setBounds(0, 0, 730, 80);

        panelDetalhesMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N
        panelDetalhesMedico.setLayout(null);

        labelCodigo.setText("Código:");
        panelDetalhesMedico.add(labelCodigo);
        labelCodigo.setBounds(30, 30, 70, 16);

        textfieldCodigo.setEditable(false);
        textfieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCodigoActionPerformed(evt);
            }
        });
        panelDetalhesMedico.add(textfieldCodigo);
        textfieldCodigo.setBounds(30, 50, 64, 22);

        labelCrm.setText("CRM");
        panelDetalhesMedico.add(labelCrm);
        labelCrm.setBounds(170, 30, 26, 16);
        panelDetalhesMedico.add(textFieldCrm);
        textFieldCrm.setBounds(170, 50, 130, 22);

        labelNome.setText("Nome completo:");
        panelDetalhesMedico.add(labelNome);
        labelNome.setBounds(360, 30, 110, 16);
        panelDetalhesMedico.add(textFieldNome);
        textFieldNome.setBounds(360, 50, 240, 22);

        labelTelefone.setText("Telefone:");
        panelDetalhesMedico.add(labelTelefone);
        labelTelefone.setBounds(30, 100, 70, 16);
        panelDetalhesMedico.add(textFieldTelefone);
        textFieldTelefone.setBounds(30, 120, 130, 22);

        labelEmail.setText("E-mail:");
        panelDetalhesMedico.add(labelEmail);
        labelEmail.setBounds(220, 100, 60, 16);
        panelDetalhesMedico.add(textFieldEmail);
        textFieldEmail.setBounds(220, 120, 180, 22);

        labelDataDeNascimento.setText("Data de Nascimento:");
        panelDetalhesMedico.add(labelDataDeNascimento);
        labelDataDeNascimento.setBounds(490, 100, 140, 16);

        formattedFieldDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedFieldDataDeNascimentoActionPerformed(evt);
            }
        });
        panelDetalhesMedico.add(formattedFieldDataDeNascimento);
        formattedFieldDataDeNascimento.setBounds(490, 120, 160, 22);
        try {
            formattedFieldDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    labelTabelaEspecialidades.setText("Tabela de Especialidades:");
    panelDetalhesMedico.add(labelTabelaEspecialidades);
    labelTabelaEspecialidades.setBounds(40, 170, 160, 16);

    labelEspecialidadesDoMedico.setText("Especialidades do Médico:");
    panelDetalhesMedico.add(labelEspecialidadesDoMedico);
    labelEspecialidadesDoMedico.setBounds(310, 170, 170, 16);

    jListTabelaEspecialidades.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    scrollTabelaEspecialidades.setViewportView(jListTabelaEspecialidades);

    panelDetalhesMedico.add(scrollTabelaEspecialidades);
    scrollTabelaEspecialidades.setBounds(40, 190, 150, 120);

    buttonMoverEspecialidade1.setBackground(new java.awt.Color(0, 153, 0));
    buttonMoverEspecialidade1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    buttonMoverEspecialidade1.setForeground(new java.awt.Color(255, 255, 255));
    buttonMoverEspecialidade1.setText(">");
    buttonMoverEspecialidade1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonMoverEspecialidade1ActionPerformed(evt);
        }
    });
    panelDetalhesMedico.add(buttonMoverEspecialidade1);
    buttonMoverEspecialidade1.setBounds(220, 188, 40, 40);

    buttonReturnEspecialidade.setBackground(new java.awt.Color(255, 0, 0));
    buttonReturnEspecialidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    buttonReturnEspecialidade.setForeground(new java.awt.Color(255, 255, 255));
    buttonReturnEspecialidade.setText("<");
    buttonReturnEspecialidade.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonReturnEspecialidadeActionPerformed(evt);
        }
    });
    panelDetalhesMedico.add(buttonReturnEspecialidade);
    buttonReturnEspecialidade.setBounds(220, 240, 40, 40);

    jListEspecialidadesdoMedico.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    scrollEspecialidadesdoMedico.setViewportView(jListEspecialidadesdoMedico);

    panelDetalhesMedico.add(scrollEspecialidadesdoMedico);
    scrollEspecialidadesdoMedico.setBounds(310, 190, 160, 120);

    getContentPane().add(panelDetalhesMedico);
    panelDetalhesMedico.setBounds(10, 100, 710, 340);

    buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancelar.png"))); // NOI18N
    buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCancelarActionPerformed(evt);
        }
    });
    getContentPane().add(buttonCancelar);
    buttonCancelar.setBounds(480, 450, 38, 60);

    buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salve-.png"))); // NOI18N
    buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonSalvarActionPerformed(evt);
        }
    });
    getContentPane().add(buttonSalvar);
    buttonSalvar.setBounds(590, 450, 38, 60);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCodigoActionPerformed

    private void formattedFieldDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedFieldDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedFieldDataDeNascimentoActionPerformed

    private void buttonReturnEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReturnEspecialidadeActionPerformed

    private void buttonMoverEspecialidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoverEspecialidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMoverEspecialidade1ActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if (operacao == OperacaoEnum.ADICIONAR) {
            adicionar();
        } else {
            
        }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonMoverEspecialidade1;
    private javax.swing.JButton buttonReturnEspecialidade;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JFormattedTextField formattedFieldDataDeNascimento;
    private javax.swing.JList<String> jListEspecialidadesdoMedico;
    private javax.swing.JList<String> jListTabelaEspecialidades;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelCrm;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEspecialidadesDoMedico;
    private javax.swing.JLabel labelMedicoAdicionar;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTabelaEspecialidades;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel panelCabeçalho;
    private javax.swing.JPanel panelDetalhesMedico;
    private javax.swing.JScrollPane scrollEspecialidadesdoMedico;
    private javax.swing.JScrollPane scrollTabelaEspecialidades;
    private javax.swing.JTextField textFieldCrm;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldTelefone;
    private javax.swing.JTextField textfieldCodigo;
    // End of variables declaration//GEN-END:variables

    private void preencherTitulo() {
        labelMedicoAdicionar.setText("Médico -" + operacao);
        if (operacao == OperacaoEnum.EDITAR) {
            labelMedicoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editaricone.png")));
        } else {
            labelMedicoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png")));
        }
    }

    private void preencherFormulario() {
        textfieldCodigo.setText(medico.getCodigo().toString());
        textFieldCrm.setText(medico.getCrm());
        textFieldNome.setText(medico.getNome());
        textFieldTelefone.setText(medico.getTelefone());
        textFieldEmail.setText(medico.getEmail());
        formattedFieldDataDeNascimento.setText(medico.getdataDeNascimento()
                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
    }

    private void adicionar() {
        CharSequence teste = " ";
        
        if (textFieldCrm.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldCrm.requestFocus();
        } else if (textFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldNome.requestFocus();
        } else if (textFieldEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldEmail.requestFocus();
        } else if (textFieldTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldTelefone.requestFocus();
        } else if (formattedFieldDataDeNascimento.getText().contains(teste) == true){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            formattedFieldDataDeNascimento.requestFocus();
        } else {
           
        }
    }
}
