/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.MedicoDAO;
import javax.swing.JTable;

/**
 *
 * @author 22282790
 */
public class PanelMedicos extends javax.swing.JPanel {
   
    private int linha;
    
    public PanelMedicos() {
        initComponents();
        MedicoDAO.criarListaDeMedicos();
        preencherTabela();
    }
    
    private int getLinha() {
        linha = tableMedicos.getSelectedRow();
        return linha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollMedicos = new javax.swing.JScrollPane();
        tableMedicos = new javax.swing.JTable();
        buttonExcluirMédico = new javax.swing.JButton();
        buttonEditarMedico = new javax.swing.JButton();
        buttonGravarMedico = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Médicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 153, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 350));
        setLayout(null);

        tableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollMedicos.setViewportView(tableMedicos);

        add(scrollMedicos);
        scrollMedicos.setBounds(10, 30, 780, 230);

        buttonExcluirMédico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/excluir.png"))); // NOI18N
        buttonExcluirMédico.setToolTipText("Excluir o médico selecionado");
        buttonExcluirMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirMédicoActionPerformed(evt);
            }
        });
        add(buttonExcluirMédico);
        buttonExcluirMédico.setBounds(520, 270, 80, 50);

        buttonEditarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editaricone.png"))); // NOI18N
        buttonEditarMedico.setToolTipText("Editar o médico selecionado");
        buttonEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarMedicoActionPerformed(evt);
            }
        });
        add(buttonEditarMedico);
        buttonEditarMedico.setBounds(610, 270, 80, 50);

        buttonGravarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/plus.png"))); // NOI18N
        buttonGravarMedico.setToolTipText("Adicionar médico");
        buttonGravarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarMedicoActionPerformed(evt);
            }
        });
        add(buttonGravarMedico);
        buttonGravarMedico.setBounds(700, 270, 80, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExcluirMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirMédicoActionPerformed

     
    }//GEN-LAST:event_buttonExcluirMédicoActionPerformed

    private void buttonEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarMedicoActionPerformed

    
    }//GEN-LAST:event_buttonEditarMedicoActionPerformed

    private void buttonGravarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarMedicoActionPerformed
     
    }//GEN-LAST:event_buttonGravarMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarMedico;
    private javax.swing.JButton buttonExcluirMédico;
    private javax.swing.JButton buttonGravarMedico;
    private javax.swing.JScrollPane scrollMedicos;
    private javax.swing.JTable tableMedicos;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        tableMedicos.setModel(MedicoDAO.getTabelaMedicos());
        ajustarTabela();
    }

    private void ajustarTabela() {
        // Impedir que o usuário movimente as colunas
        tableMedicos.getTableHeader().setReorderingAllowed(false);

        // Bloquear a edição das células da tabela
        tableMedicos.setDefaultEditor(Object.class, null);

        // Definir a largura das colunas
        tableMedicos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableMedicos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableMedicos.getColumnModel().getColumn(1).setPreferredWidth(300);
        tableMedicos.getColumnModel().getColumn(2).setPreferredWidth(360);
    }
}
