/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282790
 */
public class PanelPacientes extends javax.swing.JPanel {

    public PanelPacientes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPacientes = new javax.swing.JScrollPane();
        tablePacientes = new javax.swing.JTable();
        buttonExcluirPaciente = new javax.swing.JButton();
        buttonEditarPaciente = new javax.swing.JButton();
        buttonAdicionarPaciente = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 153, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 350));
        setLayout(null);

        tablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPacientes.setViewportView(tablePacientes);

        add(scrollPacientes);
        scrollPacientes.setBounds(12, 30, 780, 290);

        buttonExcluirPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/excluir.png"))); // NOI18N
        buttonExcluirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirPacienteActionPerformed(evt);
            }
        });
        add(buttonExcluirPaciente);
        buttonExcluirPaciente.setBounds(550, 330, 60, 40);

        buttonEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editaricone.png"))); // NOI18N
        buttonEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarPacienteActionPerformed(evt);
            }
        });
        add(buttonEditarPaciente);
        buttonEditarPaciente.setBounds(630, 330, 60, 40);

        buttonAdicionarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png"))); // NOI18N
        buttonAdicionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPacienteActionPerformed(evt);
            }
        });
        add(buttonAdicionarPaciente);
        buttonAdicionarPaciente.setBounds(710, 330, 60, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExcluirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirPacienteActionPerformed
     
    }//GEN-LAST:event_buttonExcluirPacienteActionPerformed

    private void buttonEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarPacienteActionPerformed
 
    }//GEN-LAST:event_buttonEditarPacienteActionPerformed

    private void buttonAdicionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPacienteActionPerformed
   
    }//GEN-LAST:event_buttonAdicionarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPaciente;
    private javax.swing.JButton buttonEditarPaciente;
    private javax.swing.JButton buttonExcluirPaciente;
    private javax.swing.JScrollPane scrollPacientes;
    private javax.swing.JTable tablePacientes;
    // End of variables declaration//GEN-END:variables
}
