/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.OperacaoEnum;
import br.senai.sp.jandira.model.PlanoDeSaude;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282790
 */
public class PlanosDeSaudeDialog extends javax.swing.JDialog {

    private PlanoDeSaude planoDeSaude;
    private OperacaoEnum operacao;

    /**
     * Creates new form PlanosDeSaudeDialog
     */
    public PlanosDeSaudeDialog(java.awt.Frame parent,
            boolean modal,
            OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        this.operacao = operacao;
        preencherTitulo();
    }

    public PlanosDeSaudeDialog(java.awt.Frame parent, boolean modal,
            PlanoDeSaude p,
            OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        planoDeSaude = p;
        this.operacao = operacao;
        preencherFormulario();
        preencherTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdicionarPlanoDeSaude = new javax.swing.JLabel();
        panelDetalhesPlanoDeSaude = new javax.swing.JPanel();
        labelCódigo = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        labelOperadora = new javax.swing.JLabel();
        textFieldOperadora = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        textFieldNumero = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        textFieldCategoria = new javax.swing.JTextField();
        labelValidade = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonGravarPlanoDeSaude = new javax.swing.JButton();
        formattedFieldDataDeValidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 465));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        labelAdicionarPlanoDeSaude.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAdicionarPlanoDeSaude.setForeground(new java.awt.Color(0, 0, 0));
        labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png"))); // NOI18N
        labelAdicionarPlanoDeSaude.setText("Planos de Saúde - EDITAR");
        jPanel1.add(labelAdicionarPlanoDeSaude);
        labelAdicionarPlanoDeSaude.setBounds(30, 10, 310, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 80);

        panelDetalhesPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Plano de Saúde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        panelDetalhesPlanoDeSaude.setLayout(null);

        labelCódigo.setText("Código");
        panelDetalhesPlanoDeSaude.add(labelCódigo);
        labelCódigo.setBounds(20, 30, 50, 16);

        textFieldCodigo.setEditable(false);
        textFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCodigoActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(textFieldCodigo);
        textFieldCodigo.setBounds(20, 50, 64, 22);

        labelOperadora.setText("Operadora");
        panelDetalhesPlanoDeSaude.add(labelOperadora);
        labelOperadora.setBounds(20, 150, 70, 16);
        panelDetalhesPlanoDeSaude.add(textFieldOperadora);
        textFieldOperadora.setBounds(20, 170, 100, 22);

        labelNumero.setText("Número");
        panelDetalhesPlanoDeSaude.add(labelNumero);
        labelNumero.setBounds(20, 90, 60, 16);
        panelDetalhesPlanoDeSaude.add(textFieldNumero);
        textFieldNumero.setBounds(20, 110, 150, 22);

        labelCategoria.setText("Categoria");
        panelDetalhesPlanoDeSaude.add(labelCategoria);
        labelCategoria.setBounds(20, 210, 80, 16);
        panelDetalhesPlanoDeSaude.add(textFieldCategoria);
        textFieldCategoria.setBounds(20, 230, 90, 22);

        labelValidade.setText("Data de validade");
        panelDetalhesPlanoDeSaude.add(labelValidade);
        labelValidade.setBounds(410, 40, 110, 16);

        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancelar.png"))); // NOI18N
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(buttonCancelar);
        buttonCancelar.setBounds(380, 250, 80, 50);

        buttonGravarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salve-.png"))); // NOI18N
        buttonGravarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarPlanoDeSaudeActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(buttonGravarPlanoDeSaude);
        buttonGravarPlanoDeSaude.setBounds(480, 250, 80, 50);

        formattedFieldDataDeValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedFieldDataDeValidadeActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(formattedFieldDataDeValidade);
        formattedFieldDataDeValidade.setBounds(380, 60, 160, 22);
        try {
            formattedFieldDataDeValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    getContentPane().add(panelDetalhesPlanoDeSaude);
    panelDetalhesPlanoDeSaude.setBounds(10, 100, 580, 340);

    setBounds(0, 0, 600, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonGravarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarPlanoDeSaudeActionPerformed
                
        if (operacao == OperacaoEnum.ADICIONAR) {
            adicionar();
        } else {
            editar();
        }
    }//GEN-LAST:event_buttonGravarPlanoDeSaudeActionPerformed

    private void textFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCodigoActionPerformed

    private void formattedFieldDataDeValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedFieldDataDeValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedFieldDataDeValidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    private void adicionar() {
        
        
        CharSequence teste = " ";

        if (textFieldOperadora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldOperadora.requestFocus();
        } else if (textFieldNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldNumero.requestFocus();
        } else if (textFieldCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            textFieldCategoria.requestFocus();
        } else if (formattedFieldDataDeValidade.getText().contains(teste) == true) {
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos");
            formattedFieldDataDeValidade.requestFocus();
        } else {

            PlanoDeSaude novoPlanoDeSaude = new PlanoDeSaude(textFieldOperadora.getText(),
                    textFieldNumero.getText(), textFieldCategoria.getText(),
                    LocalDate.parse(formattedFieldDataDeValidade.getText(),
                            DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            
            PlanoDeSaudeDAO.gravar(novoPlanoDeSaude);

            JOptionPane.showMessageDialog(this,
                    "Plano de saúde salvo com sucesso",
                    "Planos de saúde",
                    JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("xpto xpto");
            
            dispose();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonGravarPlanoDeSaude;
    private javax.swing.JFormattedTextField formattedFieldDataDeValidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdicionarPlanoDeSaude;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCódigo;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelOperadora;
    private javax.swing.JLabel labelValidade;
    private javax.swing.JPanel panelDetalhesPlanoDeSaude;
    private javax.swing.JTextField textFieldCategoria;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldNumero;
    private javax.swing.JTextField textFieldOperadora;
    // End of variables declaration//GEN-END:variables

    private void preencherFormulario() {
        textFieldCodigo.setText(planoDeSaude.getCodigo().toString());
        textFieldNumero.setText(planoDeSaude.getNumero());
        textFieldOperadora.setText(planoDeSaude.getOperadora());
        textFieldCategoria.setText(planoDeSaude.getCategoria());
        formattedFieldDataDeValidade.setText(planoDeSaude.getValidade().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
    }

    private void preencherTitulo() {
        labelAdicionarPlanoDeSaude.setText("Planos de Saúde - " + operacao);
        if (operacao == OperacaoEnum.EDITAR) {
            labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editaricone.png")));
        } else {
            labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png")));
        }
    }

    private void editar() {
        
        planoDeSaude.setNumero(textFieldNumero.getText());
        planoDeSaude.setCategoria(textFieldCategoria.getText());
        planoDeSaude.setOperadora(textFieldOperadora.getText());
        planoDeSaude.setValidade(LocalDate.parse(formattedFieldDataDeValidade.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        PlanoDeSaudeDAO.atualizar(planoDeSaude);

        JOptionPane.showMessageDialog(rootPane,
                "Plano de Saúde atualizado com sucesso!",
                "Planos de Saúde",
                JOptionPane.WARNING_MESSAGE);
        
        dispose();
    }
}
