/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.model.OperacaoEnum;
import br.senai.sp.jandira.model.PlanoDeSaude;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author 22282790
 */
public class PlanosDeSaudeDialog extends javax.swing.JDialog {

    private PlanoDeSaude planoDeSaude;
    private OperacaoEnum operacao;
    
    /**
     * Creates new form PlanosDeSaudeDialog
     */
    public PlanosDeSaudeDialog(java.awt.Frame parent, boolean modal,
            OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
    }

    public PlanosDeSaudeDialog(java.awt.Frame parent, boolean modal,
            PlanoDeSaude p,
            OperacaoEnum operacao) {
        super(parent, modal);
        initComponents();
        preencherFormulario();
        preencherTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdicionarPlanoDeSaude = new javax.swing.JLabel();
        panelDetalhesPlanoDeSaude = new javax.swing.JPanel();
        labelCódigo = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        labelOperadora = new javax.swing.JLabel();
        textFieldOperadora = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        textFieldNumero = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        textFieldCategoria = new javax.swing.JTextField();
        labelValidade = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonGravarPlanoDeSaude = new javax.swing.JButton();
        textFieldValidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 465));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        labelAdicionarPlanoDeSaude.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAdicionarPlanoDeSaude.setForeground(new java.awt.Color(0, 0, 0));
        labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png"))); // NOI18N
        labelAdicionarPlanoDeSaude.setText("Planos de Saúde - EDITAR");
        jPanel1.add(labelAdicionarPlanoDeSaude);
        labelAdicionarPlanoDeSaude.setBounds(30, 10, 310, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 80);

        panelDetalhesPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Plano de Saúde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        panelDetalhesPlanoDeSaude.setLayout(null);

        labelCódigo.setText("Código");
        panelDetalhesPlanoDeSaude.add(labelCódigo);
        labelCódigo.setBounds(20, 30, 50, 16);
        panelDetalhesPlanoDeSaude.add(textFieldCodigo);
        textFieldCodigo.setBounds(20, 50, 64, 22);

        labelOperadora.setText("Operadora");
        panelDetalhesPlanoDeSaude.add(labelOperadora);
        labelOperadora.setBounds(20, 150, 70, 16);
        panelDetalhesPlanoDeSaude.add(textFieldOperadora);
        textFieldOperadora.setBounds(20, 170, 100, 22);

        labelNumero.setText("Número");
        panelDetalhesPlanoDeSaude.add(labelNumero);
        labelNumero.setBounds(20, 90, 60, 16);
        panelDetalhesPlanoDeSaude.add(textFieldNumero);
        textFieldNumero.setBounds(20, 110, 150, 22);

        labelCategoria.setText("Categoria");
        panelDetalhesPlanoDeSaude.add(labelCategoria);
        labelCategoria.setBounds(20, 210, 80, 16);
        panelDetalhesPlanoDeSaude.add(textFieldCategoria);
        textFieldCategoria.setBounds(20, 230, 90, 22);

        labelValidade.setText("Data de validade");
        panelDetalhesPlanoDeSaude.add(labelValidade);
        labelValidade.setBounds(410, 40, 110, 16);

        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancelar.png"))); // NOI18N
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(buttonCancelar);
        buttonCancelar.setBounds(380, 250, 80, 50);

        buttonGravarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salve-.png"))); // NOI18N
        buttonGravarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarPlanoDeSaudeActionPerformed(evt);
            }
        });
        panelDetalhesPlanoDeSaude.add(buttonGravarPlanoDeSaude);
        buttonGravarPlanoDeSaude.setBounds(480, 250, 80, 50);
        panelDetalhesPlanoDeSaude.add(textFieldValidade);
        textFieldValidade.setBounds(370, 60, 170, 22);

        getContentPane().add(panelDetalhesPlanoDeSaude);
        panelDetalhesPlanoDeSaude.setBounds(10, 100, 580, 340);

        setBounds(0, 0, 600, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonGravarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarPlanoDeSaudeActionPerformed

    }//GEN-LAST:event_buttonGravarPlanoDeSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    private void adicionar() {
        PlanoDeSaude novoPlanoDeSaude = new PlanoDeSaude(
                textFieldOperadora.getText(),
                textFieldNumero.getText(),
                textFieldCategoria.getText(),
                LocalDate.parse(textFieldValidade.getText(), DateTimeFormatter.ISO_DATE));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonGravarPlanoDeSaude;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdicionarPlanoDeSaude;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCódigo;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelOperadora;
    private javax.swing.JLabel labelValidade;
    private javax.swing.JPanel panelDetalhesPlanoDeSaude;
    private javax.swing.JTextField textFieldCategoria;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldNumero;
    private javax.swing.JTextField textFieldOperadora;
    private javax.swing.JTextField textFieldValidade;
    // End of variables declaration//GEN-END:variables

    private void preencherFormulario() {
       textFieldCodigo.setText(planoDeSaude.getCodigo().toString());
       textFieldNumero.setText(planoDeSaude.getNumero());
       textFieldOperadora.setText(planoDeSaude.getOperadora());
       textFieldCategoria.setText(planoDeSaude.getCategoria());
    }

    private void preencherTitulo() {
        labelAdicionarPlanoDeSaude.setText("Planos de Saúde - " + operacao);
        if(operacao == OperacaoEnum.EDITAR){
            labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editaricone.png")));
        } else {
            labelAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar.png")));
        }
}
}
